# Generated by Django 5.2.4 on 2025-08-05 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Incredients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('fat', models.FloatField(help_text='Fat content in grams per 100g')),
                ('sugar', models.FloatField(help_text='sugar content in grams per 100g')),
                ('proteins', models.FloatField(help_text='proteins content in grams per 100g')),
                ('carbohydrates', models.FloatField(help_text='carbohydrates content in grams per 100g')),
                ('vitamins', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Meals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/meals')),
                ('description', models.TextField(blank=True, null=True)),
                ('disease', models.CharField(choices=[('d1', 'D1'), ('d2', 'D2')], max_length=200)),
            ],
        ),
    ]
