# Generated by Django 5.2.4 on 2025-08-05 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meals',
            name='disease',
            field=models.CharField(choices=[('D1', 'd1'), ('d2', 'D2')], max_length=200),
        ),
    ]
