# Generated by Django 5.2.4 on 2025-08-05 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0002_alter_meals_disease'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Incredients',
            new_name='Ingredients',
        ),
        migrations.AlterField(
            model_name='meals',
            name='disease',
            field=models.CharField(choices=[('d1', 'D1'), ('d2', 'D2')], max_length=200),
        ),
    ]
