# Generated by Django 5.2.4 on 2025-08-05 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0003_rename_incredients_ingredients_alter_meals_disease'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meals',
            name='disease',
            field=models.CharField(choices=[('diabetes', 'Diabetes'), ('Insomnia', 'insomnia')], max_length=200),
        ),
    ]
