# Generated by Django 5.2.4 on 2025-08-05 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0004_alter_meals_disease'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meals',
            old_name='disease',
            new_name='category',
        ),
    ]
