# Generated by Django 5.2.4 on 2025-08-08 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0005_rename_disease_meals_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Ingredients',
        ),
        migrations.RemoveField(
            model_name='meals',
            name='description',
        ),
        migrations.AddField(
            model_name='meals',
            name='Ingredients',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='meals',
            name='category',
            field=models.CharField(choices=[('Breakfast', 'breakfast'), ('Lunch', 'lunch'), ('Dinner', 'dinner')], max_length=200),
        ),
        migrations.AddField(
            model_name='disease',
            name='meals',
            field=models.ManyToManyField(related_name='disease', to='meals.meals'),
        ),
    ]
