# Generated by Django 5.2.4 on 2025-08-08 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0006_disease_delete_ingredients_remove_meals_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disease',
            name='meals',
        ),
        migrations.RemoveField(
            model_name='meals',
            name='Ingredients',
        ),
        migrations.RemoveField(
            model_name='meals',
            name='category',
        ),
        migrations.RemoveField(
            model_name='meals',
            name='image',
        ),
        migrations.AddField(
            model_name='meals',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='meals',
            name='diseases',
            field=models.ManyToManyField(related_name='meals', to='meals.disease'),
        ),
        migrations.AlterField(
            model_name='disease',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='meals',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
