# Generated by Django 5.2.4 on 2025-08-08 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0007_remove_disease_meals_remove_meals_ingredients_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meals',
            name='category',
            field=models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner')], null=True),
        ),
        migrations.AddField(
            model_name='meals',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/uploads/Meals'),
        ),
        migrations.AddField(
            model_name='meals',
            name='nutrients',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='meals',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
