# Generated by Django 5.2.5 on 2025-08-22 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0008_meals_category_meals_image_meals_nutrients_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meals',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/Meals'),
        ),
    ]
