# Generated by Django 5.2.5 on 2025-08-29 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0011_alter_meals_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meals',
            name='image',
            field=models.ImageField(blank=True, upload_to='uploads/meals'),
        ),
    ]
